fix #11: Translate Core/Keyed/GameplayCommands.txt
Ludeon/RimWorld-Belarusian pull request #39
Opened 2023-08-12 21:31 UTC by SampleText2k77

Пратэсціравана на Linux-версіі гульні (1.4.3704 Core + Biotech + Ideology + Royalty), 1920x1080.

Стварыў адзін PR з #28, #31, #32 для зручнасці тэсціравання.

2023-08-12 22:08 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateTogglePowerLabel>Прызначыць пераключэнне сілкавання</CommandDesignateTogglePowerLabel>
Я б такі адступіла ад арыгіналу тут і напісала б проста "Пераключыць сілкаванне" бо 
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/a3d289b4-57ae-4198-9695-f7db2da402f5)
нязручненька неяк.

2023-08-12 22:10 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateTogglePowerDesc>Прызначыць пераключэнне сілкавання для гэтай штукі. Сяленец хутка прыйдзе, каб пстрыкнуць пераключальнік.</CommandDesignateTogglePowerDesc>
Мне заўсёды падавалася "штукі" больш размоўнае. Я б скарыстала "рэчы".
Каментар можна зачыніць без змен, бо гэта хутчэй суб'ектыўная рэч тут.

2023-08-12 22:23 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandTryReconnectLabel>Перападлучыцца</CommandTryReconnectLabel>
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/3ab10b18-5efe-4884-9b26-1ca1dd67f79a)
Можа скараціць неяк? =( Ці і гэтак нармальна?

2023-08-12 22:29 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandTryReconnectDesc>Паспрабаваць падлучыцца да іншай крыніцы сілкавання ў межах майго радыуса падлучэння. Гэта карысна, калі я падлучаны да абясточанай сеткі, але побач ёсць сілкаваная сетка.<
"падлучаны" Можа нам варта ўлічваць род? Напрыклад, лямпа не "ён".  
То бок ці "падлучаны(а)" ці пазбягаць форм з родам. 
Ці гэтак сойдзе? =(

2023-08-12 22:34 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandGatherSpotToggleDescActive>Актыўнае - сяленцы будуць збірацца вакол гэтага аб'екта.</CommandGatherSpotToggleDescActive>
Можа ў нашай мове ":" падыдзе больш за "-"?

2023-08-12 22:39 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandToggleDraftDesc>Пераключыць жаўнерскі прызыў.\n\nПрызваныя людзі атрымліваюць загады і б'юцца. Яны не будуць працаваць, есці або адпачываць.</CommandToggleDraftDesc>
Я бы скарыстала "ваююць" бо біцца яны і паміж сабой могуць. Але гэтак ужо прычэпка, можна зарэзолвіць каментар без змен.

2023-08-12 22:43 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandClearPrioritizedWork>Ачысціць прыярытызаваную працу</CommandClearPrioritizedWork>
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/28f70ded-6814-41a1-978e-8da83bf30cc7)
Можа скараціць "прыярытызаваную" неяк?

2023-08-12 23:00 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandExtractShellDesc>Выгружае бягучы снарад, каб можна было замяніць яго на іншую зброю.</CommandExtractShellDesc>
Мне падаецца зброя - гэта больш сама турэль (ці аўтаматы там), а снарад хутчэй будзе боепрыпасам.

2023-08-12 23:03 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <MessageTurretWontFireBecauseHoldFire>Папярэджанне: мінамёт не паліць, таму што задана налада «Утрымліваць пальбу».</MessageTurretWontFireBecauseHoldFire>
Проста ўдакладненне: у арыгінале будучы час (won't = will not), няма праблем з карыстаннем часу цяперашнега, гэта мае сэнс у гульне? (не магу хутка праверыць гэта сама, выбачаюся)

2023-08-12 23:19 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandMakeBeaconStockpileDesc>Стварыць такі склад вакол гэтага будынка, які будзе супадаць з радыусам дзеяння маяка.</CommandMakeBeaconStockpileDesc>
nit: Думаю без "такі" будзе гучаць лепш.

2023-08-12 23:20 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandSunLampMakeGrowingZoneDesc>Стварыць такую зону росту вакол гэтага будынка, якая будзе супадаць з радыусам дзеяння лямпы.</CommandSunLampMakeGrowingZoneDesc>
nit: Думаю без "такую" будзе гучаць лепш.

2023-08-12 23:22 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandAutoRearm>Аўтаматычная пераўзбройка</CommandAutoRearm>
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/3e73b0e5-df81-402c-a87b-b1c5a67d90c1)
=( Можа скараціць "аўтаматачная"? І ці бедзу правільным скарыстаць "пераўзброй" (таму што меньш літар)?

2023-08-12 23:28 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandReleaseAnimalsDesc>Калі ўключана, свойскія жывёлы адпраўляюцца атакаваць аддаленыя мішэні. Калі адключана, яны застаюцца побач з гаспадаром і сцерагуць яго.</CommandReleaseAnimalsDesc>
Пераклад добры, проста прапаную сінонім: вартаваць замест сцерагчы. Можна зачыніць каментар без змен і адказу.

2023-08-12 23:30 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandReload_NoAmmo>Для пераўзбройкі патрабуецца {COUNT} адзінак {lookup: {AMMO_label}; Case; 1}</CommandReload_NoAmmo>
{lookup: {AMMO_label}; Case; 1} - о, а што гэта робіць?

2023-08-12 23:32 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
>    <CommandFormCaravanDescAtSpot>TODO</CommandFormCaravanDescAtSpot>
Чаму прапушчана?

2023-08-12 23:34 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandFormCaravan>Сфарміраваць караван</CommandFormCaravan>
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/e2693bbe-00de-4cec-a8fc-777f6bc41d88)
Пакідаем так ці трэба падумаць як перарабіць?

2023-08-12 23:37 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandCancelFormingCaravan>Скасаваць фарміраванне каравана</CommandCancelFormingCaravan>
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/a166d91e-a73b-412f-8edf-02f26d5a705e)
Пакідаем так ці трэба падумаць як перарабіць?

2023-08-12 23:40 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandShowMap>Павялічыць маштаб</CommandShowMap>
Пры пстрыку на гэтую кнопку ты загружаешся на кавалку мапы, дзе ты можаш кіраваць персанажамі, як у селешчу. "Павялічыць маштаб" па мне не вельмі добра супадае з гэтым. Можа нешта кшталту "наблізіць"?

2023-08-12 23:42 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandTradeFailNoNegotiator>Няма ніводнага прытомнага чалавека, хто здольны весці перамовы.</CommandTradeFailNoNegotiator>
nit: Можа такі пакінуць "і здольнага"? Думаю гэты надпіс будзе нават калі ўсё прытомныя, але не могуць весьці размовы па характырыстыкам. Хаця можна і так пакінуць, не бачу асаблівай розніцы.

2023-08-12 23:43 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandFulfillTradeOfferFailInsufficient>Ваш караван павінен мець {0}, каб задаволіць гандлёвую прапанову.</CommandFulfillTradeOfferFailInsufficient>
Не будзе тут праблем у склоне {0}, не правяралі?

2023-08-12 23:45 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandTakeOffConfirmation>Вы ўпэўнены, што жадаеце запусціць карабель?\n\nКожны на гэтай тэрыторыі пакіне планету, астатнія застануцца.</CommandTakeOffConfirmation>
nit: "left behind" мае негатыўную афабоўку. Яны не проста застануцца, яны будуць пакінуты тут. Можа варта гэтую афарбоўку перанесьці ў пераклад і заменіць "застануцца" на нешта больш негатыўнае?

2023-08-12 23:47 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandSetTargetFuelLevel>Задаць мэтавы ўзровень паліва</CommandSetTargetFuelLevel>
Не магу гэта праверыць у гульне зараз, але мне падаецца гэта можа выглядаць страшна. Вы не правяралі?

2023-08-12 23:49 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandToggleAllowAutoRefuel>Пераключыць аўтаматычную перазапраўку</CommandToggleAllowAutoRefuel>
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/b6cf6f65-2c0f-4eac-bbec-27bae63c37ae)
Трэба неяк выправіць =( Можа проста "Аўтаматычная перазапраўка" і скараціць слова аўтаматычная?

2023-08-12 23:57 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandAutoloadTransportersDesc>Пераключыць загрузку ўсяго неабходнага грузу па меры таго, як ён становіцца наяўным.</CommandAutoloadTransportersDesc>
Наяўны хутчэй "мець", а "available" хутчэй "даступным". Ці я неправільна разумею "наяўны"?

2023-08-12 23:59 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandSelectPreviousTransporterDesc>Вылучыць папярэдні транспартны под у гэтай групе запуску.</CommandSelectPreviousTransporterDesc>
Вышэй под быў перакладзены, як капсула.

2023-08-12 23:59 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandSelectAllTransportersDesc>Вылучыць усе транспартныя поды ў гэтай групе запуску.</CommandSelectAllTransportersDesc>
Вышэй под быў перакладзены, як капсула.

2023-08-13 00:20 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDropPawn>Кінуць {0_nameDef}</CommandDropPawn>
Не будзе тут потым праблем пасля перакладу імён? Кшталту "Кінуць Ягор"?

2023-08-13 00:22 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <TakeDrugDesc>Выбраць наркотык з інвентару, каб спажыць яго неадкладна.</TakeDrugDesc>
nit: Неадкладна ў канцы гучыць ненатуральна.
```suggestion
  <TakeDrugDesc>Выбраць наркотык з інвентару, каб неадкладна спажыць яго.</TakeDrugDesc>
```

2023-08-13 00:23 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandLeaveRitualDesc>Скончыць прымаць удзел у рытуале з назвай {RITUAL_labelDef}. Рытуал будзе працягвацца, пакуль у ім прымае ўдзел прынамсі адзін чалавек.</CommandLeaveRitualDesc>
Можа патрэбны двукоссі для назвы рытуалу?

2023-08-13 00:25 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandCancelRitualDesc>Скончыць {RITUAL_labelDef} неадкладна. Абавязак правядзення рытуалу застанецца. Вы можаце перазапусціць рытуал пазней.</CommandCancelRitualDesc>
nit: тут таксама неадкладна гучыць ненатуральна. У ангельскай мове такія словы ставяцца ў канцы, але ў нашай хутчэй у сярэдзіне ці пачатку.

2023-08-13 00:26 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandCancelRitualDesc>Скончыць {RITUAL_labelDef} неадкладна. Абавязак правядзення рытуалу застанецца. Вы можаце перазапусціць рытуал пазней.</CommandCancelRitualDesc>
"Перазапусціць рытуал" таксама гучыць неяк ненатуральна.

2023-08-13 00:31 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateOpenCloseVentLabel>Прызначыць адчыненне/зачыненне</CommandDesignateOpenCloseVentLabel>
Думаю варта нешта зрабіць з зачыненне тут 
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/e9d66964-d5d2-4ee3-b523-3bdec800d3eb)

2023-08-13 00:37 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <BuildingUnassign>Скасаваць прызначэнне</BuildingUnassign>
Я не супраць пакінуць як ёсць, але калі будзе ідэя, як зрабіць надпіс менш, я думаю, гэта будзе лепш.
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/93769140-e334-460a-b2e0-fe4d0b6f64cb)

2023-08-13 09:47 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateTogglePowerLabel>Прызначыць пераключэнне сілкавання</CommandDesignateTogglePowerLabel>
Да, такія пераклады ўсе папраўлю. Ці скарачу, ці замяню на іншае

2023-08-13 09:49 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateTogglePowerLabel>Прызначыць пераключэнне сілкавання</CommandDesignateTogglePowerLabel>
`Пераключыць сілкаванне` тут не падыходзіць. Некаторыя прадметы можа пераключыць адразу, і для гэтага ёсць асобны радок з перакладам. Астатнія пераключаюцца сяленцамі, таму тут і ёсць "Прызначыць"

2023-08-13 09:49 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateTogglePowerDesc>Прызначыць пераключэнне сілкавання для гэтай штукі. Сяленец хутка прыйдзе, каб пстрыкнуць пераключальнік.</CommandDesignateTogglePowerDesc>
Добрая прапанова

2023-08-13 09:50 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandTryReconnectLabel>Перападлучыцца</CommandTryReconnectLabel>
Будзе скарочана

2023-08-13 09:51 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandTryReconnectDesc>Паспрабаваць падлучыцца да іншай крыніцы сілкавання ў межах майго радыуса падлучэння. Гэта карысна, калі я падлучаны да абясточанай сеткі, але побач ёсць сілкаваная сетка.<
Добрая прапанова. Зраблю `падлучаны(-а)` у адпаведнасці з правіламі.

2023-08-13 09:53 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandGatherSpotToggleDescActive>Актыўнае - сяленцы будуць збірацца вакол гэтага аб'екта.</CommandGatherSpotToggleDescActive>
Згодны. Таму што можна замяніць на `Актыўнае, а менавіта сяленцы будуць....`

2023-08-13 09:53 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandClearPrioritizedWork>Ачысціць прыярытызаваную працу</CommandClearPrioritizedWork>
Будзе скарочана. Не паспеў запушыць актуальныя змены. Дзякуй

2023-08-13 09:54 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandToggleDraftDesc>Пераключыць жаўнерскі прызыў.\n\nПрызваныя людзі атрымліваюць загады і б'юцца. Яны не будуць працаваць, есці або адпачываць.</CommandToggleDraftDesc>
Трэба падумаць. Прапанова не пазбаўлена сэнсу

2023-08-13 09:56 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <MessageTurretWontFireBecauseHoldFire>Папярэджанне: мінамёт не паліць, таму што задана налада «Утрымліваць пальбу».</MessageTurretWontFireBecauseHoldFire>
Трэба замяніць як вы прапанавалі. Дзякуй

2023-08-13 10:01 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandReload_NoAmmo>Для пераўзбройкі патрабуецца {COUNT} адзінак {lookup: {AMMO_label}; Case; 1}</CommandReload_NoAmmo>
Гэта я пакуль што проста сцягнуў з перакладу на рускую: https://github.com/Ludeon/RimWorld-ru/blob/master/Core/Keyed/GameplayCommands.xml#L72

Можа будзе праверыць, калі ўсе радкі `AMMO_label` будуць перакладзены. Здаецца, там ёсць нейкі спосаб дадаць склоны да словаў, глядзі: https://github.com/Ludeon/RimWorld-ru/blob/master/Core/Strings/Words/Nouns/People_Enemies_Genitive_Plural.txt

2023-08-13 10:02 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
>    <CommandFormCaravanDescAtSpot>TODO</CommandFormCaravanDescAtSpot>
Не паспеў перакласці абноўленыя файлы. Пераклад з'явіцца з наступным пушам

2023-08-13 10:02 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandFormCaravan>Сфарміраваць караван</CommandFormCaravan>
Будзе перароблена

2023-08-13 10:02 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandCancelFormingCaravan>Скасаваць фарміраванне каравана</CommandCancelFormingCaravan>
Будзе перароблена

2023-08-13 10:03 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandFulfillTradeOfferFailInsufficient>Ваш караван павінен мець {0}, каб задаволіць гандлёвую прапанову.</CommandFulfillTradeOfferFailInsufficient>
Да, будзе праблема. Трэба дадаць lookup па склонам.

2023-08-13 10:05 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandSetTargetFuelLevel>Задаць мэтавы ўзровень паліва</CommandSetTargetFuelLevel>
Ужо прыбраў `мэтавы`, дадам у наступным пушы. Для кнопак у большасці выпадкаў ёсць подпісы, таму страціць дакладнасць тут будзе нармальна

2023-08-13 10:06 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandToggleAllowAutoRefuel>Пераключыць аўтаматычную перазапраўку</CommandToggleAllowAutoRefuel>
Выпраўлена. Дадам у наступным пушы

2023-08-13 10:10 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandAutoloadTransportersDesc>Пераключыць загрузку ўсяго неабходнага грузу па меры таго, як ён становіцца наяўным.</CommandAutoloadTransportersDesc>
У маёй галаве `даступны` сінонім `наяўны`. У слоўніку таксама: https://verbum.by/?q=available
Я вырашыў не выкарыстоўваць банальна запазычанае з рускай слова.

2023-08-13 10:10 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandAutoloadTransportersDesc>Пераключыць загрузку ўсяго неабходнага грузу па меры таго, як ён становіцца наяўным.</CommandAutoloadTransportersDesc>
Ці ёсць яшчэ нейкія сумненні наконт гэтага?

2023-08-13 10:11 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDropPawn>Кінуць {0_nameDef}</CommandDropPawn>
Прапаную зрабіць таску пад праблему са склонамі. У адсутнасці іншых спосабаў таксама прапаную пакуль што рабіць пераклады склонаў як у рускам перакладзе: з дапамогай lookup

2023-08-13 10:14 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <TakeDrugDesc>Выбраць наркотык з інвентару, каб спажыць яго неадкладна.</TakeDrugDesc>
Не бачу ненатуральнасці тут. Але ж можна і змяніць, ваш варыянт таксама падыходзіць

2023-08-13 10:15 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateOpenCloseVentLabel>Прызначыць адчыненне/зачыненне</CommandDesignateOpenCloseVentLabel>
Перарабіў на `Прызначыць адчыненне (зачыненне)`. З прабелам апошняе слова пераносіцца на наступны радок. Хутка запушу

2023-08-13 10:16 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <BuildingUnassign>Скасаваць прызначэнне</BuildingUnassign>
Такія ж думкі пра гэты пераклад. Не здолеў пакуль што прыдумаць іншы варыянт

2023-08-13 10:25 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandClearPrioritizedWork>Ачысціць прыярытызаваную працу</CommandClearPrioritizedWork>
`Ачысціць працу ў прыярытэце`

2023-08-13 10:27 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandExtractShellDesc>Выгружае бягучы снарад, каб можна было замяніць яго на іншую зброю.</CommandExtractShellDesc>
Перараблю ў `на іншыя боепрыпасы`. Адзіночнага ліку для гэтага слова не існуе ў беларускай

2023-08-13 10:28 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandMakeBeaconStockpileDesc>Стварыць такі склад вакол гэтага будынка, які будзе супадаць з радыусам дзеяння маяка.</CommandMakeBeaconStockpileDesc>
Не ўпэўнены. Тут маецца на ўвазе стварыць не проста зону росту, а менавіта "такую", "якая" будзе нешта там рабіць....

2023-08-13 11:22 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateTogglePowerLabel>Прызначыць пераключэнне сілкавання</CommandDesignateTogglePowerLabel>
Зразумела. Падумаю яшчэ, што можна зрабіць.

2023-08-13 11:27 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandMakeBeaconStockpileDesc>Стварыць такі склад вакол гэтага будынка, які будзе супадаць з радыусам дзеяння маяка.</CommandMakeBeaconStockpileDesc>
Але "зрабіць нешта, якое будзе вось такое" гучыць такжа. 
У любым выпадку гэта nit, я не маю нічога і супраць бягучага варыянта.

2023-08-13 12:53 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandMakeBeaconStockpileDesc>Стварыць такі склад вакол гэтага будынка, які будзе супадаць з радыусам дзеяння маяка.</CommandMakeBeaconStockpileDesc>
Мне трошкі рэжа вочы варыянт без `такі`. Пакіну так.

2023-08-13 13:02 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandTakeOffConfirmation>Вы ўпэўнены, што жадаеце запусціць карабель?\n\nКожны на гэтай тэрыторыі пакіне планету, астатнія застануцца.</CommandTakeOffConfirmation>
Трэба падумаць

2023-08-13 13:41 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandCancelMonumentMarkerDesc>Незваротна выдаліць метку гэтага манумента.</CommandCancelMonumentMarkerDesc>
```suggestion
  <CommandCancelMonumentMarkerDesc>Незваротна выдаліць метку гэтага помніка.</CommandCancelMonumentMarkerDesc>
```

2023-08-13 19:04 UTC, Kepkivich commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateTogglePowerLabel>Прызначыць пераключэнне сілкавання</CommandDesignateTogglePowerLabel>
Можа "Прызначыць перамыканне сікавання"?
Якраз на адну літару карацей.

2023-08-13 19:25 UTC, Kepkivich commented on Core/Keyed/GameplayCommands.xml
> +  <BuildingUnassign>Скасаваць прызначэнне</BuildingUnassign>
"Зняць/выдаліць прызначэнне"?

2023-08-13 19:29 UTC, Kepkivich commented on Core/Keyed/GameplayCommands.xml
> +  <CommandHideZoneDesc>Схаваць/скасаваць схаванне гэтай зоны.</CommandHideZoneDesc>
Чаму не:
```suggestion
  <CommandHideZoneDesc>Схаваць/паказаць гэтую зону.</CommandHideZoneDesc>
```?
Мілагучней здаецца

2023-08-13 19:55 UTC, Kepkivich commented on Core/Keyed/GameplayCommands.xml
> +  <CommandExtractShellDesc>Выгружае бягучы снарад, каб можна было замяніць яго на іншую зброю.</CommandExtractShellDesc>
![2023-08-13_224835](https://github.com/Ludeon/RimWorld-Belarusian/assets/141284485/9de8bf29-594c-4fde-9a6a-95f95b496780)
Расейска-беларускі слоўнік 1997-га году прапануе такі варыянт.
Даволі пурыстычна, ды і інтуітыўна разумела.

2023-08-13 20:01 UTC, Kepkivich commented on Core/Keyed/GameplayCommands.xml
> +  <CommandShipLaunchDesc>Пачаць дзеянні па запуску карабля з бягучай канфігурацыяй.</CommandShipLaunchDesc>
```suggestion
  <CommandShipLaunchDesc>Пачаць працэс запуску карабля з бягучай канфігурацыяй.</CommandShipLaunchDesc>
```

2023-08-13 20:06 UTC, Kepkivich commented on Core/Keyed/GameplayCommands.xml
> +  <CommandToggleDoorHoldOpen>Утрымліваць адчыненымі</CommandToggleDoorHoldOpen>
```suggestion
  <CommandToggleDoorHoldOpen>Трымаць адчыненымі</CommandToggleDoorHoldOpen>
```
У гаворке такой варыянт выключна чуў. Прычэпка, можна ігнараваць.

2023-08-14 05:33 UTC, Kepkivich approved these changes

2023-08-14 08:42 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandSunLampMakeGrowingZoneDesc>Стварыць такую зону росту вакол гэтага будынка, якая будзе супадаць з радыусам дзеяння лямпы.</CommandSunLampMakeGrowingZoneDesc>
Рэжа вочы варыянт без `такую`. Пакіну так у гэтым выпадку

2023-08-18 07:17 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateTogglePowerLabel>Прызначыць пераключэнне сілкавання</CommandDesignateTogglePowerLabel>
Ці сапраўды `перамыканне` = `пераключэнне`? Слоўнік кажа, што першы варыянт мае іншае значэнне: https://verbum.by/?q=%D0%BF%D0%B5%D1%80%D0%B0%D0%BC%D0%BA%D0%BD%D1%83%D1%86%D1%8C

2023-08-18 07:20 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandToggleDraftDesc>Пераключыць жаўнерскі прызыў.\n\nПрызваныя людзі атрымліваюць загады і б'юцца. Яны не будуць працаваць, есці або адпачываць.</CommandToggleDraftDesc>
Можа паспрабаваць варыянт `...атрымліваюць загады і вядуць бой`?

2023-08-18 07:21 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandAutoloadTransportersDesc>Пераключыць загрузку ўсяго неабходнага грузу па меры таго, як ён становіцца наяўным.</CommandAutoloadTransportersDesc>
Адкройце зноў, калі ласка, калі з'явяцца яшчэ нейкія думкі наконт гэтай прапановы

2023-08-19 22:33 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandDesignateTogglePowerLabel>Прызначыць пераключэнне сілкавання</CommandDesignateTogglePowerLabel>
Скараціў у гэтым выпадку. Калі ласка, адкройце канфу зноў, калі ёсць яшчэ нейкія думкі

2023-08-19 22:34 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandToggleDraftDesc>Пераключыць жаўнерскі прызыў.\n\nПрызваныя людзі атрымліваюць загады і б'юцца. Яны не будуць працаваць, есці або адпачываць.</CommandToggleDraftDesc>
Выбраў "ваююць", так як два чалавекі прагаласавалі за гэты варыянт

2023-08-19 22:35 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandTakeOffConfirmation>Вы ўпэўнены, што жадаеце запусціць карабель?\n\nКожны на гэтай тэрыторыі пакіне планету, астатнія застануцца.</CommandTakeOffConfirmation>
Закрою, таму што nit. Не выдумаў іншага варыянту

2023-08-19 22:36 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandLeaveRitualDesc>Скончыць прымаць удзел у рытуале з назвай {RITUAL_labelDef}. Рытуал будзе працягвацца, пакуль у ім прымае ўдзел прынамсі адзін чалавек.</CommandLeaveRitualDesc>
Выдаліў двукоссі і не стаў іх выкарыстоўваць. Назвы рытуалаў звычайна не бяруцца ў двукоссі

2023-08-19 22:43 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandBuildCopyDesc>Пабудаваць копію гэтага будынка.</CommandBuildCopyDesc>
Тут і у іншых месцах `будынак` -> `пабудова`. Напрыклад, можна пабудаваць копію лямпы, яна не з'яўляецца будынкам

2023-08-20 02:42 UTC, MaryAlex commented
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/1df9c651-e853-47e7-b00a-cbedfa7d276c)
IMO: выглядае неяк перагружанна, што лічыцца не вельмі добрым UI. (не ведаю дзеянне тут, проста кажу, хутчэй)

2023-08-20 03:35 UTC, MaryAlex commented on Core/Keyed/GameplayCommands.xml
> +  <CommandTryReconnectLabel>Падлучыцца да іншай крыніцы</CommandTryReconnectLabel><!-- Кароткі варыянт "Перападлучыцца" не ўлазіць у кнопку -->
Можа лепш скараціць слова "Перападлучыцца"?

2023-08-20 09:09 UTC, SampleText2k77 commented
> ![image](https://user-images.githubusercontent.com/15628733/261828121-1df9c651-e853-47e7-b00a-cbedfa7d276c.png) IMO: выглядае неяк перагружанна, што лічыцца не вельмі добрым UI. (не ведаю дзеянне тут, проста кажу, хутчэй)

Давай паспрабую перарабіць неяк

2023-08-20 09:09 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandTryReconnectLabel>Падлучыцца да іншай крыніцы</CommandTryReconnectLabel><!-- Кароткі варыянт "Перападлучыцца" не ўлазіць у кнопку -->
Спачатку быў такі варыянт) Але ён не ўлазіць у кнопку

2023-08-21 10:05 UTC, RedRibbon297 requested changes

2023-08-24 18:08 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandForbiddenDesc>Забаронена: вашым сяленцам не дазволена ўзаемадзейнічаць з гэтым. Клікніце, каб дазволіць.</CommandForbiddenDesc>
Не згодны, што прапанаваныя варыянты лепш. Карыстацца - гэта ўсё ж у сваіх інтарэсах, але заданні могуць быць і не звязаныя з карыстаннем. Напрыклад, перанесці дазволены аб'ект на іншы склад. Гэта ўсё ж больш пра ўзаемадеянне на маю думку.

Другі варыянт таксама недакладны, таму што калі ў сяленца рэжым вар'яцтва, ён усё ж будзе ўзаемадейнічаць з прадметам. Напрыклад, яму не дазволена паліць, але ён будзе рабіць гэта, таму што яму ў гэты момант усё роўна на забароны

2023-08-24 18:10 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandFireAtWillDesc>Пераключыць пальбу па жаданні.\n\nКалі адключана, гэты персанаж не будзе аўтаматычна страляць па аддаленым мішэням. Не ўплывае на блізкі бой.</CommandFireAtWillDesc>
`пераключыць` - гэта ж і ёсць `уключыць або выключыць`. Не разумею, чаму бягучы варыянт трэба замяніць на прапанаваны вамі.

2023-08-24 18:11 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandHideZoneDesc>Схаваць/паказаць гэтую зону.</CommandHideZoneDesc>
Чаму

2023-08-24 18:14 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandSettleDesc>Пасяліцца на гэтай тэрыторыі. Вашы сяленцы ўвайдуць на гэту тэрыторыю і будуць здольны пачаць будаўніцтва новага дому.</CommandSettleDesc>
Чаму трэба перарабіць на такі варыянт?

2023-08-24 18:20 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandAbandonHome>Закінуць</CommandAbandonHome>
> але заставацца на гэтым месцы.

У тлумачальным слоўніку няма такой падрабязнасці. Астатнее больш пра `закінуць`, чым пра `пакінуць`. І `пакінуць` часцей для перакладу `leave` выкарыстоўваецца

2023-08-24 18:21 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandCancelFormingCaravan>Скасаваць фармірав. каравана</CommandCancelFormingCaravan><!-- Скарочана, бо не ўлазіць у кнопку -->
Толькі лепш `збіранне`, здаецца

2023-08-24 18:21 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandToggleAllowAutoRefuel>Пераключ. аўтамат. перазапраўку</CommandToggleAllowAutoRefuel><!-- Скарочана, бо не ўлазіць у кнопку -->
Не ўлазіць у подпіс

2023-08-24 18:44 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandStopAttackFailNotForceAttacking>Прымусовая атака не ў працэсе.</CommandStopAttackFailNotForceAttacking>
Прапанаваныя варыянты здаюцца мне дрэннымі, але я згодны, што трэба перарабіць. Выберу больш мілагучны варыянт

2023-08-24 18:47 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandAutoRearm>Аўтаматыч. пераўзброй.</CommandAutoRearm><!-- Скарочана, бо не ўлазіць у кнопку -->
`Аўтазамена` можна. Змяняць = change, замяняць = replace/rearm/etc.

2023-08-24 18:50 UTC, SampleText2k77 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandToggleAllowAutoRefuel>Пераключ. аўтамат. перазапраўку</CommandToggleAllowAutoRefuel><!-- Скарочана, бо не ўлазіць у кнопку -->
`Запраўляць аўтаматычна` улазіць

2023-08-24 19:32 UTC, RedRibbon297 approved these changes

2023-09-03 15:55 UTC, MaryAlex approved these changes

2023-09-03 21:01 UTC, merged